export const SET_TARGET_CURRENCY = 'SET_TARGET_CURRENCY';
export const LOAD_GENERAL_DATA = 'LOAD_GENERAL_DATA';
export const LOAD_GENERAL_DATA_SUCCESS = 'LOAD_GENERAL_DATA_SUCCESS';
export const LOAD_GENERAL_DATA_FAILURE = 'LOAD_GENERAL_DATA_FAILURE';

