export const SET_TARGET_CURRENCY = 'SET_TARGET_CURRENCY';
export const LOAD_GENERAL_DATA = 'LOAD_GENERAL_DATA';
export const LOAD_GENERAL_DATA_SUCCESS = 'LOAD_GENERAL_DATA_SUCCESS';
export const LOAD_GENERAL_DATA_FAILURE = 'LOAD_GENERAL_DATA_FAILURE';
export const ADD_OWNED_CURRENCY = 'ADD_OWNED_CURRENCY';
export const LOAD_DETAILED_DATA = 'LOAD_DETAILED_DATA';
export const LOAD_DETAILED_DATA_SUCCESS = 'LOAD_DETAILED_DATA_SUCCESS';
export const LOAD_DETAILED_DATA_FAILURE = 'LOAD_DETAILED_DATA_FAILURE';
export const REMOVE_OWNED_CURRENCY = 'REMOVE_OWNED_CURRENCY';

export const MAIN_COLOR = '#3498db';
